remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

title: Yansiel Melendez - Cybersecurity Specialist
description: A professional portfolio showcasing my skills, projects, and achievements in cybersecurity.

# Theme Configuration
minimal_mistakes_skin: dark
