title: "Yansiel Melendez Portfolio"
description: "Portfolio showcasing cybersecurity skills, certifications, and projects."
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Enable GitHub-flavored markdown
markdown: kramdown
kramdown:
  input: GFM
