# Site settings
title: "Yansiel Melendez | Cybersecurity Specialist"
description: "Welcome to my portfolio site. Explore my journey in cybersecurity."
baseurl: "" # Leave empty if deploying at the root
url: "https://yourusername.github.io" # Replace with your GitHub Pages URL

# Theme settings
theme: minima
minima:
  skin: null # Disable Minima's default styles to use custom CSS

# SASS processing
sass:
  style: compressed

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Include the custom CSS in the build
include:
  - docs/assets/css/style.css
