# Site settings
title: "Yansiel Melendez Portfolio"
description: "Portfolio website showcasing my skills, certifications, and projects in cybersecurity."
url: "https://yourusername.github.io" # Replace with your GitHub Pages URL
baseurl: "" # Leave empty unless you use a custom domain

# Author details
author:
  name: "Yansiel Melendez"
  email: "yansiel.melendez@gmail.com"
  github: "https://github.com/YMQSec"
  linkedin: "https://www.linkedin.com/in/yansiel-melendez"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Theme
theme: minima # Replace with your chosen theme, e.g., minimal, cayman, etc.

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown
  syntax_highlighter: rouge # Syntax highlighting for code snippets

# Navigation
collections:
  projects:
    output: true
    permalink: /projects/:title/

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Pagination (optional, if you want blog posts or project listings)
paginate: 5
paginate_path: "/page:num/"
