# Site settings
title: "Yansiel Melendez Portfolio"
description: "Portfolio website showcasing my skills, certifications, and projects in cybersecurity."
theme: minima # Change if using another GitHub Pages theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
