remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

title: Yansiel Melendez - Cybersecurity Specialist
description: A professional portfolio showcasing my skills and projects in cybersecurity.
